name: BibleEngama
description: "Bible Louis Second 1910 pro Ancien et nouveau testament"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  clipboard: ^0.1.3
  expandable: ^5.0.1
  flutter:
    sdk: flutter
  http: 1.2.2
  fluttertoast: ^8.2.4
  font_awesome_flutter: ^10.0.0
  get: ^4.6.6
  provider: ^6.1.1
  scroll_to_index: ^3.0.1
  scrollable_positioned_list: ^0.3.8
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.2.2
  share_plus: ^10.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/logo.png